### ISSUE TITLE
Support additional VM console options

### ISSUE THREAD

**Issue by nmeyerhans** [firecracker-microvm/firecracker-go-sdk#10]
We currently support several console options for the VM, including `stdio` to use the existing IO streams or `xterm` to run in a graphical terminal. Additional ones that could be useful are:

1. Arbitrary file -- Log stdout/stdio to an arbitrary file and read stdin from /dev/null
2. Inherited file descriptor. -- Allow the client to provide existing file descriptors for any or all of the standard IO streams.

Maybe others?

**Comment by xibz** [comment]
closing in result of #17
