### ISSUE TITLE
Support retrieval of MMDS from firecracker

### ISSUE THREAD

**Issue by cpheps** [firecracker-microvm/firecracker-go-sdk#109]
There currently is no method on the Machine struct for retrieving metadata from Firecracker. 

There's a method to set the metadata and it looks like the client is setup to make the GET call for MMDS, I think things just need to be hooked up between the client and the Machine.

**Comment by xibz** [comment]
Hello @cpheps, thank you for reaching out to us. I think the vision there was that you would only ever need to send metadata to the machine and never need to retrieve with the SDK. That is why it is only on the client. I am not opposed to putting a helper method to retrieve metadata, but what is your use case our of curiosity?

**Comment by cpheps** [comment]
Our use case is to store some data about the Firecracker instance so if the program that launched the it dies, when it comes back up it can recreate the state of things by asking the Firecracker instances what they know about themselves.
