### ISSUE TITLE
Support Firecracker 0.18

### ISSUE THREAD

**Issue by kzys** [firecracker-microvm/firecracker-go-sdk#121]
[Fireckracker 0.18 is out](https://github.com/firecracker-microvm/firecracker/releases/tag/v0.18.0)! The biggest change is the way Firecracker supports vsock.

https://github.com/firecracker-microvm/firecracker/blob/master/docs/vsock.md

**Comment by kzys** [comment]
Note that we are going to drop 0.17.0 support instead of supporting both of them.

**Comment by sipsma** [comment]
This was closed by #129
