### ISSUE TITLE
Support Firecracker rate limiters

### ISSUE THREAD

**Issue by nmeyerhans** [firecracker-microvm/firecracker-go-sdk#13]
Firecracker supports network and disk [rate limiters](https://github.com/firecracker-microvm/firecracker/blob/master/docs/design.md#io-storage-networking-and-rate-limiting) that can help restrict access to physical resources, insulating against noisy-neighbor issues. We don't currently support configuration of these features, but should.

**Comment by Zyqsempai** [comment]
@nmeyerhans Is this still actual?

**Comment by IRCody** [comment]
@Zyqsempai I think this was already implemented in #55.
