### ISSUE TITLE
Support forcing CNI network creation even if delete of pre-existing network fails

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker-go-sdk#130]
[In reference to the current code's attempt to delete a pre-existing network for a given VM](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/e4d1f825a38ade07bd1e9dc2bfd64abb7f0331f2/network.go#L324-L330), I've now encountered in the wild a plugin (the `firewall` CNI plugin) that consistently fails here due to a previous result not being available (which goes against what the CNI spec says).

While we can fix this problem upstream, we should probably also include the ability for users to optionally override failing at that line (perhaps via something like a `Force` parameter in the CNI configuration) in order to allow use of CNI plugins that aren't perfectly compliant. The default behavior should stay the same though and if the error is overridden with the `Force` parameter then the error needs to be logged still.

**Comment by Zyqsempai** [comment]
I will work on this one!

**Comment by sipsma** [comment]
> I will work on this one!

Sounds great, thanks! Let me know if you need any more context on the change

**Comment by sipsma** [comment]
Closed by #161
