### ISSUE TITLE
Support customizing tap device name in tc-redirect-tap plugin

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker-go-sdk#131]
[Right now it's not possible for users of `tc-redirect-tap` to set a specific tap device name to use; it will always be created with the name the kernel decides (usually `tap0`)](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/e4d1f825a38ade07bd1e9dc2bfd64abb7f0331f2/cni/cmd/tc-redirect-tap/main.go#L124).

We should add support for that. We need to decide if it is best added as a `CNI_ARG` or a parameter in the CNI configuration file.

**Comment by Zyqsempai** [comment]
I will take this one!

**Comment by sipsma** [comment]
Sounds great @Zyqsempai ! I took a look at this again, my thinking right now is that it would be best to start with support for configuring the tap name through the CNI args rather than the CNI configuration file, which is probably more flexible for users.

So what that means is checking if the CNI args specified a tap name and, if so, setting it in [the plugin configuration here](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/master/cni/cmd/tc-redirect-tap/main.go#L124). The CNI args are accessible in the `args.Args` field of [the object provided to us here](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/5fb4eeae40c2d36188185e5fda3eb7d306e51b96/cni/cmd/tc-redirect-tap/main.go#L94). We will need to define a key name for specifying the tap name, something simple but namespaced like `TC_REDIRECT_TAP_NAME` is probably sufficient.

Let me know if that makes sense! Thanks again.

**Comment by kzys** [comment]
Thanks @Zyqsempai! Resolving.
