### ISSUE TITLE
Support customizing tap device uid/gid in tc-redirect-tap plugin

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker-go-sdk#132]
[Right now it's not possible for users of tc-redirect-tap to set a specific tap uid/gid to use; it will always be created with the uid/gid of the caller](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/e4d1f825a38ade07bd1e9dc2bfd64abb7f0331f2/cni/cmd/tc-redirect-tap/main.go#L126-L128).

We should add support for customizing the uid/gid. We need to decide if it is best added as a CNI_ARG or a parameter in the CNI configuration file.

**Comment by Zyqsempai** [comment]
I will work on this one.

**Comment by sipsma** [comment]
Great, this will be fairly similar to what I described in [the issue for supporting tap name](https://github.com/firecracker-microvm/firecracker-go-sdk/issues/131#issuecomment-540245061), but instead adding support for overriding [the uid/gid fields here](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/5fb4eeae40c2d36188185e5fda3eb7d306e51b96/cni/cmd/tc-redirect-tap/main.go#L126-L128).

This again will require defining keys to use for these fields, something like `TC_REDIRECT_TAP_UID` and `TC_REDIRECT_TAP_GID` should be good I think.

**Comment by kzys** [comment]
Thanks @Zyqsempai. Resolving this one too 💯
