### ISSUE TITLE
Add Firecracker vsock client code

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker-go-sdk#136]
The recent vsock changes in Firecracker v0.18.0 result in some additional requirements on top of the previously-used standard vsock interface (for which there are already 3rd party libraries), [see their docs](https://github.com/firecracker-microvm/firecracker/blob/master/docs/vsock.md) and [this PR for example](https://github.com/firecracker-microvm/firecracker-containerd/pull/266).

Given there is now Firecracker-specific logic to interfacing with vsock, it would make sense for the Go SDK to contain that code rather than have all consumers of the Go SDK be forced to reimplement it themselves.

**Comment by Zyqsempai** [comment]
@sipsma Is this still actual for us? Can I work on this one?

**Comment by sipsma** [comment]
@Zyqsempai this is still something we'd like to do, though I'd caution that it will require a lot of cross-repo changes/coordination (since we'd basically just be migrating pieces of this firecracker-containerd code to this repo: https://github.com/firecracker-microvm/firecracker-containerd/blob/master/internal/vm/vsock.go ) and I'd suspect the hardest part by far would just be finding a way to write a test for the code in this repo.

The problem with the testing part is that this can really only be verified with an integ test that creates a real VM with some custom process running on the inside that uses the VM-guest-side of the vsock client implementation. That's easy to do in firecracker-containerd because we already have an agent process running in the VM, but we don't really have anything (to my knowledge) setup in this firecracker-go-sdk repo to enable that sort of test. It'd require some thought/design and potentially changes to how the CI works in this repo.

Overall, my opinion is that this wouldn't be the best issue for an external contributor unfortunately. There's some other issues in this repo I can point you to if interested that might be more workable ([such as this one](https://github.com/firecracker-microvm/firecracker-go-sdk/issues/130)).

**Comment by Zyqsempai** [comment]
@sipsma Thank you for letting me know, after your explanation, I am more than agree with you, actually, I didn't thought it's such a global change, I will take a look into other issues, thank you!

**Comment by kzys** [comment]
Resolved by #380 finally!
