### ISSUE TITLE
Support for tc-redirect-tap in experimental Firecracker frakti runtime

### ISSUE THREAD

**Issue by photoszzt** [firecracker-microvm/firecracker-go-sdk#139]
After adding the tc-redirect-tap to the cni configuration, the pod based on docker fails to connect to network. Is it possible to make them usable for both runtime? For the context, I'm using frakti which supports multiple runtime.

**Comment by photoszzt** [comment]
I create two network config files. One for docker and one for firecracker. It seems working fine for now.

**Comment by sipsma** [comment]
@photoszzt Thanks for reaching out! Just to clarify, you are now able to use tc-redirect-tap successfully without it interfering with docker?

Is it possible to post the CNI configuration you were trying to use previously with both runtimes (the one that didn't work)? At the moment,`tc-redirect-tap` will likely only be usable by the `firecracker-go-sdk`, but I'm interested in the details of your usecase to see what changes we could make to `tc-redirect-tap` that might result in broader compatibility.

**Comment by photoszzt** [comment]
Yes. I pass them different net config in two directories. One has the tc-redirect-tap and one doesn't. That seems to solve my problem. 

For docker:
```json
{
    "cniVersion": "0.3.1",
    "name": "mynet",
    "plugins": [
        {
            "type": "bridge",
            "bridge": "cni0",
            "isGateway": true,
            "ipMasq": true,
            "ipam": {
                "type": "host-local",
                "subnet": "10.30.0.0/16",
                "routes": [
                    { "dst": "0.0.0.0/0"   }
                ]
            }
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        }
    ]
}
```
For firecracker:
```
{
    "cniVersion": "0.3.1",
    "name": "fcmynet",
    "plugins": [
        {
            "type": "bridge",
            "bridge": "cni-fc0",
            "isGateway": true,
            "ipMasq": true,
            "ipam": {
                "type": "host-local",
                "subnet": "10.30.0.0/16",
                "routes": [
                    { "dst": "0.0.0.0/0"   }
                ]
            }
        },
        {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
        },
        {
            "type": "tc-redirect-tap"
        }
    ]
}
```
You can see the only difference is the firecracker config has the chained tc-redirect-tap plugin.

**Comment by sipsma** [comment]
@photoszzt awesome, understand now and glad to hear it's working for you. I think using a separate configuration like you've done is the right approach here.

The reason `tc-redirect-tap` will not work when used with other frameworks like Docker is that `tc-redirect-tap` modifies the previous interface from the CNI configuration (in your case, the `bridge`) to mirror all of its traffic with a tap device that's intended to be plugged into a Firecracker VM. However, docker likely doesn't know anything about this tap device and tries to just use the bridge, which results in all network traffic going to an unused tap device, essentially a blackhole. 

When `tc-redirect-tap` is used with the `firecracker-go-sdk` on the other hand, the tap device will be plugged into a Firecracker VM, so any traffic on the bridge's interface will be mirrored with the VM's network interface.

Thanks again for reaching out, let us know if anything else comes up. Resolving this issue for now as things appear to be working as expected.

**Comment by photoszzt** [comment]
I haven't tested it thoroughly. There's still some problem with the tc-redirect-tap. With the above firecracker setting, I can't pass the liveness/readness check. Is the bridge plugin tested with tc-redirect-tap?

**Comment by photoszzt** [comment]
The problem I'm having is the liveness probe and readiness probe are all failed:

  Warning  Unhealthy  45s                kubelet, 127.0.0.1  Liveness probe failed: Get http://10.30.0.12:8080/_/health: dial tcp 10.30.0.12:8080: connect: no route to host
  Warning  Unhealthy  43s (x3 over 47s)  kubelet, 127.0.0.1  Readiness probe failed: Get http://10.30.0.12:8080/_/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  43s (x2 over 47s)  kubelet, 127.0.0.1  Liveness probe failed: Get http://10.30.0.12:8080/_/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by sipsma** [comment]
@photoszzt I saw you mentioned earlier that you are trying to use frakti, which I'm personally not very familiar with. Can you provide more details on the frakti configuration you are using to create these VMs, such as what runtime you are using?

It's not immediately clear from the frakti docs how customizable the runtime configuration is, but unless the runtime you're using is based on something using the Firecracker Go SDK, it's unlikely it will currently work with `tc-redirect-tap`. However, I'd be interested to know more about how you're using frakti to see if it's possible to update `tc-redirect-tap` to be more broadly compatible.

**Comment by photoszzt** [comment]
I'm modifying frakti to support firecracker. They already have a unikernel runtime that's based on libvirt and I'm adding a firecracker backend to it. 

I'm not sure whether my network configuration is setup correctly. Here's what I do to pass network configuration: https://github.com/photoszzt/frakti/blob/314e995c7d0df808ea4e3a43cc7dd67a29731b29/pkg/ocicni/ocicni.go#L257-L278
Or the following code: 
```golang
func (plugin *cniNetworkPlugin) FCNetworkInterface(podID string, metadata *kubeapi.PodSandboxMetadata) firecracker.NetworkInterface {
	plugin.syncNetworkConfig()
	defaultNetwork := plugin.getDefaultNetwork()
	confType := defaultNetwork.NetworkConfig.Plugins[0].Network.Type
	// Search for vendor-specific plugins as well as default plugins in the CNI codebase.
	vendorDir := vendorCNIDir(plugin.vendorCNIDirPrefix, confType)
	return firecracker.NetworkInterface{
		CNIConfiguration: &firecracker.CNIConfiguration{
			NetworkName: defaultNetwork.NetworkConfig.Name,
			IfName:      DefaultInterfaceName,
			Args: [][2]string{
				{"IgnoreUnknown", "1"},
				{"K8S_POD_NAME", metadata.GetName()},
				{"K8S_POD_NAMESPACE", metadata.GetNamespace()},
				{"K8S_POD_INFRA_CONTAINER_ID", podID},
			},
			BinPath:  append(plugin.pluginDirs, vendorDir),
			ConfDir:  plugin.netDir,
			CacheDir: "",
		},
	}
}
```

**Comment by photoszzt** [comment]
@sipsma I update the submodule. I create a fork of the go sdk so that I can use the older version of cni. The tc-redirect-tap command is built using the original repo. If you want to build it, you can pull the repo.

**Comment by sipsma** [comment]
Thanks @photoszzt , first of all your project sounds very neat! It's really cool to see potential Firecracker integration with frakti.

For the issue you are experiencing, I will take a closer look at your code the next few days when I have some time to get a better overall understanding. I'll also see if I can use your CNI configuration (bridge+portmapping+tc-redirect-tap) with the separate firecracker-containerd project (where we have some tests of tc-redirect-tap w/ a veth plugin), to make sure all the plugins are working correctly with each other. Will update later this week or early next week.

In the meantime, for the health check issue there are a probably a lot of places this could be failing. One initial thing to try though: are you able to `ping` the IP being used for the health check (i.e. w/ an ICMP ping packet, not an HTTP request)? This can help test whether the issue lies with the networking setup or with the HTTP health server.

**Comment by sipsma** [comment]
One update: I tried using your CNI configuration (bridge->portmap->tc-redirect-tap) with firecracker-containerd and was successfully able to get networking up and running. I could reach the internet from within the Firecracker VM and was able to connect to ports being listened on inside the VM from the host (tested with netcat).

So I think `tc-redirect-tap` should be expected to basically work with the bridge and portmap plugins. I haven't had a chance to look at your code in depth yet, but I think a good place to start would be to verify that your health server is running as expected inside the VM and is running with the "host" network namespace (which in practice actually means the network namespace of the guest VM).

**Comment by photoszzt** [comment]
@sipsma I print out the osv log. It's hanging at waiting for ip. 
```
bsd: initializing - done
VFS: mounting ramfs at /
VFS: mounting devfs at /dev
net: initializing - done
Detected virtio-mmio device: (2,0)
Detected virtio-mmio device: (1,0)
queue 0 size 256
queue 1 size 256
queue 2 size 0
eth0: ethernet address: 8a:a0:42:f0:16:6c
queue 0 size 256
queue 1 size 0
virtio-blk: Add blk device instances 0 as vblk0, devsize=536870912
Warning: No hardware source of entropy available to your platform,
	CSPRNG will rely on software source of entropy to provide high-quality randomness.
random: <Software, Yarrow> initialized
VFS: unmounting /dev
VFS: mounting rofs at /rofs
failed to mount /rofs, error = No error information
VFS: mounting zfs at /zfs
zfs: mounting osv/zfs from device /dev/vblk0.1
VFS: mounting devfs at /dev
VFS: mounting procfs at /proc
VFS: mounting sysfs at /sys
random: device unblocked.
program zpool.so returned 1
BSD shrinker: event handler list found: 0xffffa00000985080
	BSD shrinker found: 1
BSD shrinker: unlocked, running
[I/26 dhcp]: Broadcasting DHCPDISCOVER message with xid: [1713505748]
[I/26 dhcp]: Waiting for IP...
```
In my local setup with NAT, it prints like this:
```
[I/26 dhcp]: Broadcasting DHCPDISCOVER message with xid: [1850312527]
[I/26 dhcp]: Waiting for IP...
[I/26 dhcp]: Broadcasting DHCPDISCOVER message with xid: [1771944366]
[I/26 dhcp]: Waiting for IP...
[I/26 dhcp]: Broadcasting DHCPDISCOVER message with xid: [1285738661]
[I/26 dhcp]: Waiting for IP...
[I/26 dhcp]: Broadcasting DHCPDISCOVER message with xid: [1533719522]
[I/26 dhcp]: Waiting for IP...
[I/195 dhcp]: Received DHCPOFFER message from DHCP server: 192.168.100.1 regarding offerred IP address: 192.168.100.173
[I/195 dhcp]: Broadcasting DHCPREQUEST message with xid: [1533719522] to SELECT offered IP: 192.168.100.173
[I/195 dhcp]: Received DHCPOFFER message from DHCP server: 192.168.100.1 regarding offerred IP address: 192.168.100.173
[W/195 dhcp]: Got packet with wrong transaction ID (1533719522, 1285738661)
[I/195 dhcp]: DHCP received hostname: osv

[I/195 dhcp]: Received DHCPACK message from DHCP server: 192.168.100.1 regarding offerred IP address: 192.168.100.173
[I/195 dhcp]: Server acknowledged IP 192.168.100.173 for interface eth0 with time to lease in seconds: 3600
eth0: 192.168.100.173
[I/195 dhcp]: Configuring eth0: ip 192.168.100.173 subnet mask 255.255.255.0 gateway 192.168.100.1 MTU 1500
[I/195 dhcp]: Set hostname to: osv
```

**Comment by photoszzt** [comment]
@sipsma It might be an osv issue. I can reach the health endpoint locally. Do you know any way I can test the CNI setup without launching kubernetes?

**Comment by photoszzt** [comment]
@sipsma I fix the osv issue. Osv can get the ip that's returned by the cni configuration. But the client still cannot connect to the VM. The client is executed in the same network namespace with the server. Is there anything I need to pay attention to?

**Comment by sipsma** [comment]
@photoszzt I'm not familiar with frakti or osv, so can you describe the overall architecture here a bit more? My main question is where osv fits into all of this. I see in your code that the CreateContainer implementation starts a Firecracker VM, so does osv run inside of the VM? Is it configured to start when the VM boots?

If the above understanding is correct, you said that osv can get the IP that's returned by the CNI configuration, so that means that you're able to see in logs that osv starts and uses the statically configured IP within the VM? But then when the health check runs, it makes a request to that same IP from the host and doesn't get a response?

**Comment by photoszzt** [comment]
@sipsma No, Firecracker directly starts osv directly. Unikernel is a VM. It doesn't need to run another VM. I modify the go sdk to suite osv's convention as it has different assumption on boot argument and disk format. Mostly following osv's upstream script: https://github.com/cloudius-systems/osv/blob/master/scripts/firecracker.py

 Osv get the IP that's returned by the CNI configuration. I can see in the logs that osv starts and uses the statically configured IP. I can make a request to the same IP from the host and it respond when I run the VM without kubernetes. But if I make the client runs in the same network namespace of the VM, then the client cannot reach the VM.  

if I run the VM with kubernetes using similar setup, the health check fails. It's failing because of no route to host.

**Comment by sipsma** [comment]
> But if I make the client runs in the same network namespace of the VM, then the client cannot reach the VM.

Ah okay, so you are outside the VM (i.e. not in the guest) but inside the network namespace on the host while trying to reach a service listening on the VM IP inside the VM. It's actually expected behavior that you'd not be able to reach a service running inside the VM from **within the network namespace on the host**, you should only be able to reach the services running inside the VM **from outside the network namespace**.

I can get into the gory details of why that's the expected behavior if you're interested (it's a bit convoluted), but basically the rule is once you've setup a network namespace w/ tc-redirect-tap you should only connect to the VM IP from outside that network namespace.

Getting back to the Kubernetes health checks, is it the case that the health checks run inside the network namespace of the VM? That could be one reason they are failing. If so, can you configure the health checks to be run outside the network namespace? I'm not familiar enough with Kubernetes to know if that's possible.

**Comment by photoszzt** [comment]
@sipsma There's one more complication. The sender is held in a docker container in another network namespace. Docker and firecracker take two different network configurations. In my example, they are on two different bridges. I'm not sure they can talk to each other.

**Comment by sipsma** [comment]
So the health check client is running in a separate docker container? Yeah that would definitely introduce a whole new layer of networking to deal with.

Have you tried specifying the same name for the bridge in both CNI configuration files? That is, keep using separate CNI configuration files but specify `"bridge": "cni"` in both of them? 

On the surface, it seems like the bridge plugin *might* support re-using an existing bridge (but I have not tried this before): https://github.com/containernetworking/plugins/blob/411d060b81745df3744ad43011a61fdfae1fcf49/plugins/main/bridge/bridge.go#L230-L233

**Comment by photoszzt** [comment]
Yes, it's telling me connection refused now. I'm not sure what filters the packet. Tcpdump on cni0 shows the packet is sending to the VM.

**Comment by sipsma** [comment]
"Connection refused" typically means that the packet actually reached the destination IP (i.e. it wasn't filtered), but the OS at the destination is reporting there's no service listening on the requested port. This makes it sound like the packets are being routed correctly, but the health server is not actually up and running listening on the port. Can you see any confirmation in logs that there is a health server listening on the VM IP and correct port?

**Comment by photoszzt** [comment]
@sipsma It's indeed the server's problem. The VM's memory is not large enough to start it. Thanks for your help!

**Comment by sipsma** [comment]
@photoszzt Of course, glad you got it figured out! Please reach out if you run into anything else we can help with
