### ISSUE TITLE
Update to Firecracker v0.19

### ISSUE THREAD

**Issue by sipsma** [firecracker-microvm/firecracker-go-sdk#141]
There's a new release of Firecracker that has some tweaks to the new vsock API which require updates in the SDK: https://github.com/firecracker-microvm/firecracker/releases/tag/v0.19.0

**Comment by Zyqsempai** [comment]
I will take this one!

**Comment by kzys** [comment]
Thanks @Zyqsempai! Resolving, since we have its release task as #137.
