### ISSUE TITLE
Startup Hangs when using LogWriter

### ISSUE THREAD

**Issue by cpheps** [firecracker-microvm/firecracker-go-sdk#143]
This pertains to PR #134 I worked on and it introduced the issue. 

When it was suggested to move `captureFifoToFile` to the handler, I forgot about the fact that if Firecracker is not started before we start listening on the log.fifo then `os.Open` in [captureFifoToFile](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/master/machine.go#L582) will block. Since we moved `captureFifoToFile` to a handler, this blocks the handlers which execute before we start Firecracker so it'll never unblock., shown [here](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/master/machine.go#L329-L334).

Mostly creating this issue to spark a discussion on the best place to put captureFifoToFile. The implementation before the above PR did not work with Jailer as the sdk jailer setup would change the path to the `LogFifo` in the config before we tried to listen on it.

I've outlined workflows from what I understand needs to happen in the case of jailer and plain firecracker.

Firecracker:
- Create `log.fifo` and `metric.fifo`
- Start Firecracker
- Configure logging and metrics via API
- Call `captureFifoToFile`

Jailer:
- Create `log.fifo` and `metric.fifo`
- Jailer chroot for vm setup
- Hard link `log.fifo` and `metric.fifo` into jailer chroot for VM
- Jailer start Firecracker
- Configure logging and metrics via API
- Call `captureFifoToFile` on original `log.fifo` path (not hard linked)

**Comment by cpheps** [comment]
Investigating this more, now that I've dug into it seems like the VM is started but we try and listen to the fifos before we tell Firecracker about them. Seems like `captureFifoToFile` should be in `BootstrapLoggingHandler` (which was originally how things were). The issue there is jailer messes with the fifo paths in the config.

**Comment by xibz** [comment]
@cpheps - Hello, thank you for taking a deep dive into this. I am a little confused to why `captureFifoToFile` now blocks. Can you elaborate on that a little? Why does enabling jailer cause it to block?

**Comment by cpheps** [comment]
So jailer itself isn't the issue with hanging. There was an issue previously where using the `FifoLogWriter` wouldn't work if you were using jailer and your original `log.fifo` location was not `./log.fifo`. That is no longer an issue but it should be considered when implementing a fix. I'll elaborate on it more at the bottom.

The current hanging issue happens when you have a `FifoLogWriter` specified in either a jailer or non-jailer configuration.

The main issue lies in this chunk of code from [handlers.go](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/master/handlers.go#L259-L261).

```Go
var defaultFcInitHandlerList = HandlerList{}.Append(
	SetupNetworkHandler,
	SetupKernelArgsHandler,
	StartVMMHandler,
	CreateLogFilesHandler,
	BootstrapLoggingHandler,
	CreateMachineHandler,
	CreateBootSourceHandler,
	AttachDrivesHandler,
	CreateNetworkInterfacesHandler,
	AddVsocksHandler,
)
```

We currently call `captureFifoToFile` inside `CreateLogFilesHandler` which is before `BootstrapLoggingHandler`. When we do the `os.Open` inside `captureFifoToFile` it hangs since we have not sent the `PUT /logger`, which is inside `BootstrapLoggingHandler`. This means Firecracker is not sending down either `log.fifo` or `metric.fifo`. The behavior when doing a read only open on a fifo pipe is to block until something sends down the pipe.

Based on that it would make sense to move `captureFifoToFile` into `BootstrapLoggingHandler` after we send the `PUT /logger` API call to Firecracker. This was the original behavior but there is an issue with this when using jailer. In `jail.go` This chunk of code sets the `LinkFilesHandler` to be after `CreateLogFilesHandlerName` but before `BootstrapLoggingHandler`

```Go
// AdaptHandlers will inject the LinkFilesHandler into the handler list.
func (s NaiveChrootStrategy) AdaptHandlers(handlers *Handlers) error {
	if !handlers.FcInit.Has(CreateLogFilesHandlerName) {
		return ErrRequiredHandlerMissing
	}

	handlers.FcInit = handlers.FcInit.AppendAfter(
		CreateLogFilesHandlerName,
		LinkFilesHandler(filepath.Join(s.Rootfs, rootfsFolderName), filepath.Base(s.KernelImagePath)),
	)

	return nil
}
```

The `LinkFilesHandler` modifies the configuration values for `LogFifo` and `MetricsFifo` to point to the hard links inside the vm chroot as seen here:

```Go
			for _, fifoPath := range []*string{&m.Cfg.LogFifo, &m.Cfg.MetricsFifo} {
				if fifoPath == nil || *fifoPath == "" {
					continue
				}

				fileName := filepath.Base(*fifoPath)
				if err := linkFileToRootFS(
					m.Cfg.JailerCfg,
					filepath.Join(rootfs, fileName),
					*fifoPath,
				); err != nil {
					return err
				}

				if err := os.Chown(filepath.Join(rootfs, fileName), *m.Cfg.JailerCfg.UID, *m.Cfg.JailerCfg.GID); err != nil {
					return err
				}

				// update fifoPath as jailer works relative to the chroot dir
                               // This overwrites the user config!!!!!
				*fifoPath = fileName
			}
```

Now that the config has been changed when `captureFifoToFile` is called inside of `BootstrapLoggingHandler` it attempts to create a log writer pointing at the hard links which have a relative path inside the vm chroot. It will accidentally work if your original config values for `LogFifo` and `MetricFifo` are `./log.fifo` and `./metrics.fifo` respectively.

It's a bit of confusing issue so hopefully the explanation makes sense. I don't have a great solution for this yet, wanted to see what the core dev team thought about it.

**Comment by xibz** [comment]
@cpheps - I went ahead and create a PR for a fix. I tested this and ensured that this is properly working with the fifo writer. Please let me know if you run into any other issues.
