### ISSUE TITLE
CNI, ip= kernel argument and multiple interfaces

### ISSUE THREAD

**Issue by smira** [firecracker-microvm/firecracker-go-sdk#173]
Linux kernel image we're using has compiled-in support for bonding, so if we use it with Firecracker, it comes up with `eth0` and `bond0` interfaces by default. When firecracker does CNI, it injects `ip=` kernel argument (and doesn't allow that argument to be passed in) with final IP assigned to the VM, but it skips specifying actual device name: https://github.com/firecracker-microvm/firecracker-go-sdk/blob/master/cni/vmconf/vmconf.go#L120-L122

In our case this leads to kernel trying to use `bond0` which is obviously not configurable. 

I have two options here, so asking which one is preferable (I can submit a PR):

1. We use `static` CNI, so we know IP address in advance, and we can build `ip=` kernel argument before VM is launched. So first option is to skip setting `ip=` kernel argument based on config: https://github.com/firecracker-microvm/firecracker-go-sdk/blob/master/machine.go#L392-L396

2. Second option is to add interface name to machine config, and pass it through the layers so that code in `vmconf.go` can use explicit interface name if configured, or leave it empty as it is today. 

Which way looks better for the project?

**Comment by kzys** [comment]
Sorry for not responding the issue and thanks for the contribution. Can we resolve this issue now?

**Comment by smira** [comment]
@kzys, yes, closing that PR #178 resolved it as option (2). thanks!
