### ISSUE TITLE
jailer: flag seccomp-level is not supported anymore 

### ISSUE THREAD

**Issue by muhamadazmy** [firecracker-microvm/firecracker-go-sdk#175]
The jailer on the master branch has dropped the `--seccomp-level` flag [here](https://github.com/firecracker-microvm/firecracker/compare/v0.20.0...master#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR19).

The sdk still append this flag to the `jailer` binary [here](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/master/jailer.go#L158)

Which causes the jailer to fail with error:
```
Arguments parsing error: Found argument 'seccomp-level' which wasn't expected, or isn't valid in this context.
```

**Comment by xibz** [comment]
Hello @muhamadazmy, thank you for reaching out to us and notifying us of the issue. I've went ahead and added a PR with the fix, #176, but we will need to update our CI to build against master. If you have any questions about the PR and other issue, please let us know

**Comment by muhamadazmy** [comment]
@xibz thank you so much for such quick response :)

**Comment by xibz** [comment]
Hey @muhamadazmy - Sorry for the delay there. We managed to get the change merged in and verified that it does work with HEAD of Firecracker. We know have a better story on how we want to deal with supporting HEAD. If you have any other issues or questions, please don't hesitate to ask.

**Comment by muhamadazmy** [comment]
Thank you so much @xibz . I really appreciate it 😊
