### ISSUE TITLE
Security error when downloading the v0.21.0

### ISSUE THREAD

**Issue by mustafaakin** [firecracker-microvm/firecracker-go-sdk#224]
Hi, I'm not sure why it happened however I get the following message when I try to download:

go: downloading github.com/firecracker-microvm/firecracker-go-sdk v0.21.0
go get github.com/firecracker-microvm/firecracker-go-sdk: github.com/firecracker-microvm/firecracker-go-sdk@v0.21.0: verifying module: checksum mismatch
        downloaded: h1:kV/PDppT1p96RGB4AGeCL3+Xy0jEV4nC4ark71DMGek=
        sum.golang.org: h1:41W/zyL3S33ZK/pNFfVrW38Y2YpNE6ZFArQOHL27V2I=

I can download the v0.20.0 fine.

**Comment by kzys** [comment]
What is your Go version? We have seen the same issue on https://github.com/firecracker-microvm/firecracker-containerd/pull/406. Seems Go 1.11 and Go 1.12 can't generate the correct checksum.

**Comment by mustafaakin** [comment]
I'm on Go 1.14.1 linux/amd

**Comment by kzys** [comment]
That's strange. What was the command you have tried? Do you have go.mod and/or go.sum in your directory?

**Comment by mustafaakin** [comment]
I just go mod init and go get back then and got the above error continously for an hour, but right now I did not get it. Not sure why it happened though. Sorry.
