### ISSUE TITLE
Split out firectl to its own repo

### ISSUE THREAD

**Issue by ilianaw** [firecracker-microvm/firecracker-go-sdk#24]
The firectl binary stands on its own, and would help make downstream packaging (namely in Amazon Linux) much less confusing.

**Comment by samuelkarp** [comment]
@ilianaw fyi I moved this issue into the firecracker-go-sdk repository, since that's where the firectl tool currently lives.

**Comment by ilianaw** [comment]
Oh, right. :sweat_smile:

**Comment by samuelkarp** [comment]
This work is blocked on #21 and #23.  After those are merged, we can split out firectl.

**Comment by kshitij8** [comment]
I see that both the blocking changes have been merged, is there a plan to break out firectl?

**Comment by samuelkarp** [comment]
@kshitij8: @nmeyerhans just started working on it

**Comment by nmeyerhans** [comment]
https://github.com/firecracker-microvm/firectl
