### ISSUE TITLE
Please release v0.22.0 of the go SDK for Firecracker 0.22.0 compatibility

### ISSUE THREAD

**Issue by bodenr** [firecracker-microvm/firecracker-go-sdk#264]
Fircracker v0.22.0 has been out since Aug 5 (https://github.com/firecracker-microvm/firecracker/commit/b68a78beabed1c2417acfe73e63df0ef7916f0cc#diff-7f337bc17ae2ea3c2f55a502b59caae0) and contains a handful of changes that are missing in the v0.21.0 of the go sdk. For example, changes in the log/metrics FIFO and API. As a result running v0.21.0 of the go sdk with 0.22.0 of FC leaves consumers with no way to address FC 0.22.0 specific changes resulting in errors like:
```
[429:ERROR:src/api_server/src/lib.rs:169] An error occurred when deserializing the json body of a request: unknown field `log_fifo`, expected one of `log_path`, `level`, `show_level`, `show_log_origin` at line 1 column 27.
```

Is there any ETA to release 0.22.0 of the go sdk so consumers can "stay current/compatible" with the latest Firecracker release?

Thank you,

**Comment by kzys** [comment]
Sorry for the late reply. We are planning to release a new version (#266) hopefully next week.

**Comment by bodenr** [comment]
Thank you for the update.
I've been watching https://github.com/firecracker-microvm/firecracker-go-sdk/pull/266 but it obviously hasn't merged yet.
Is there any new ETA for when we might expect the new release?

**Comment by xibz** [comment]
@bodenr we've run into some permission issues on the backend and we are getting those resolved. Once resolved we can do the release!

**Comment by xibz** [comment]
We just release [`v0.22.0`](https://github.com/firecracker-microvm/firecracker-go-sdk/releases/tag/v0.22.0). Please let us know if you have any other requests!

**Comment by bodenr** [comment]
@xibz thank you!
