### ISSUE TITLE
Build errors, on Windows 10

### ISSUE THREAD

**Issue by advancedwebdeveloper** [firecracker-microvm/firecracker-go-sdk#267]
Hi.
I tried to install the latest Golang 1.15.2 distro, on Windows 10.

I entered MinGW's bash:

> $ bash --version
> GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

> $go version
> go version go1.15.2 windows/amd64
My environment looks like this:

> $ go env
> go env
> set GO111MODULE=
> set GOARCH=amd64
> set GOBIN=
> set GOCACHE=C:\Users\Worker\AppData\Local\go-build
> set GOENV=C:\Users\Worker\AppData\Roaming\go\env
> set GOEXE=.exe
> set GOFLAGS=
> set GOHOSTARCH=amd64
> set GOHOSTOS=windows
> set GOINSECURE=
> set GOMODCACHE=C:\Users\Worker\go\pkg\mod
> set GONOPROXY=
> set GONOSUMDB=
> set GOOS=windows
> set GOPATH=C:\Users\Worker\go
> set GOPRIVATE=
> set GOPROXY=https://proxy.golang.org,direct
> set GOROOT=c:\go
> set GOSUMDB=sum.golang.org
> set GOTMPDIR=
> set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
> set GCCGO=gccgo
> set AR=ar
> set CC=gcc
> set CXX=g++
> set CGO_ENABLED=1
> set GOMOD=
> set CGO_CFLAGS=-g -O2
> set CGO_CPPFLAGS=
> set CGO_CXXFLAGS=-g -O2
> set CGO_FFLAGS=-g -O2
> set CGO_LDFLAGS=-g -O2
> set PKG_CONFIG=pkg-config
> set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Worker\AppData\Local\Temp\go-build149366158=/tmp/go-build -gno-record-gcc-switches
>

**Comment by advancedwebdeveloper** [comment]
I tried to obtain source & build your project:

> $ go get -u github.com/firecracker-microvm/firecracker-go-sdk
> go build github.com/containernetworking/plugins/pkg/ns: build constraints exclude all Go files in C:\Users\Worker\go\src\github.com\containernetworking\plugins\pkg\ns
> # github.com/containerd/fifo

And some problems occurred:

> ..\go\src\github.com\containerd\fifo\handle_nolinux.go:34:11: undefined: syscall.Stat_t
> ..\go\src\github.com\containerd\fifo\handle_nolinux.go:35:12: undefined: syscall.Stat
> ..\go\src\github.com\containerd\fifo\handle_nolinux.go:49:11: undefined: syscall.Stat_t
> ..\go\src\github.com\containerd\fifo\handle_nolinux.go:50:12: undefined: syscall.Stat
> ..\go\src\github.com\containerd\fifo\mkfifo_nosolaris.go:24:9: undefined: syscall.Mkfifo

so that is the question to Microsoft - but this already have an alternative approach, at Microsoft.

> # github.com/vishvananda/netlink/nl
> ..\go\src\github.com\vishvananda\netlink\nl\parse_attr.go:26:9: undefined: rtaAlignOf
> ..\go\src\github.com\vishvananda\netlink\nl\parse_attr.go:43:23: undefined: NLA_F_NESTED
> ..\go\src\github.com\vishvananda\netlink\nl\parse_attr.go:44:57: undefined: NLA_TYPE_MASK
> ..\go\src\github.com\vishvananda\netlink\nl\parse_attr.go:53:15: undefined: NLA_F_NET_BYTEORDER
> ..\go\src\github.com\vishvananda\netlink\nl\parse_attr.go:62:15: undefined: NLA_F_NET_BYTEORDER
> # github.com/vishvananda/netns
> ..\go\src\github.com\vishvananda\netns\netns.go:28:13: undefined: unix.Stat_t
> ..\go\src\github.com\vishvananda\netns\netns.go:29:12: undefined: unix.Fstat
> ..\go\src\github.com\vishvananda\netns\netns.go:32:12: undefined: unix.Fstat
> ..\go\src\github.com\vishvananda\netns\netns.go:43:8: undefined: unix.Stat_t
> ..\go\src\github.com\vishvananda\netns\netns.go:44:12: undefined: unix.Fstat
> ..\go\src\github.com\vishvananda\netns\netns.go:56:8: undefined: unix.Stat_t
> ..\go\src\github.com\vishvananda\netns\netns.go:57:12: undefined: unix.Fstat
> ..\go\src\github.com\vishvananda\netns\netns.go:71:12: undefined: unix.Close
> 

I am not familiar with that project.

CC @aboch @vishvananda @chantra @paravmellanox @corny

**Comment by kzys** [comment]
It would be hard to use the SDK on Windows. Firecracker depends on KVM which is Linux specific. Firecracker's API server is listening a Unix domain socket, which is not available in Windows.

**Comment by kzys** [comment]
Closing. The SDK launches Firecracker and communicates with that through a local Unix domain socket.

Since Firecracker doesn't support Windows as its host, running the SDK on Windows wouldn't be possible. So building the SDK on Windows would not have real-world use cases.

**Comment by maxdml** [comment]
There is a real-world use case: integrating the SDK within a larger project. Programmer experience would be better if at least it was possible to compile and run unit tests locally (which might mock the Firecracker SDK).

Here's an example: https://github.com/songgao/water/blob/master/if.go

This project implements methods for other targets (windows/linux), such that import becomes possible.

The firecracker SDK could simply return an empty response/"pass"/ "not implemented" for these.
