### ISSUE TITLE
Long-term support for gollvm

### ISSUE THREAD

**Issue by advancedwebdeveloper** [firecracker-microvm/firecracker-go-sdk#268]
Hi.
I was able to building this project with [gollvm](https://go.googlesource.com/gollvm/) - so it makes sense to run all the tests, on Linux host/bare metal/on-prem.

It would be petty helpful if there would be some end-user examples, in Go, to reproduce potential real-world scenarios - so not just basic test automation.

**Comment by kzys** [comment]
According to https://go.googlesource.com/gollvm/,

> Gollvm is currently in development -- releases are not yet available for download. Instructions for building gollvm follow.

Do you know how stable the compiler is?

**Comment by kzys** [comment]
Closing. We could reconsider once gollvm is getting stable.
