### ISSUE TITLE
Outdated Slack link

### ISSUE THREAD

**Issue by angristan** [firecracker-microvm/firecracker-go-sdk#340]
On https://github.com/firecracker-microvm/firecracker-go-sdk/blob/main/README.md#questions, the Slack link doesn't work: https://tinyurl.com/firecracker-microvm

![image](https://user-images.githubusercontent.com/11699655/116478896-187b9f80-a87f-11eb-96ae-86ccede5ec7e.png)

I suppose it should be updated as in https://github.com/firecracker-microvm/firecracker/commit/7b0f0161532692f23d648cdfd1d4cdea2c8fb65b :)

**Comment by RoyceDavison** [comment]
@angristan Thank you for pointing that out. We just created a PR for it.

**Comment by RoyceDavison** [comment]
Will close this issue once the PR is merged

**Comment by dl-stripe** [comment]
Looks like the current invite link is also not working anymore. Any chance we can generate a new one?
