### ISSUE TITLE
Intermittent LoadSnapshot integration test and examples failures due to bad rootfs.

### ISSUE THREAD

**Issue by austinvazquez** [firecracker-microvm/firecracker-go-sdk#418]
For testing `CreateSnapshot` and `LoadSnapshot` support in the SDK, we started utilizing `firecracker`'s devtool to create a microVM rootfs and SSH key for spinning up microVMs we could run commands inside using SSH. 

It would be nice to have these artifacts publicly available via S3 bucket for download compared to building it at runtime.

**Comment by austinvazquez** [comment]
The load snapshot integration test can sometimes fail with the following:

```
=== CONT  TestLoadSnapshot

    machine_test.go:2134: 

        	Error Trace:	/local/home/buildkite-agent/builds/ip-10-0-0-177-12/firecracker-microvm/firecracker-go-sdk/machine_test.go:2134

        	            				/local/home/buildkite-agent/builds/ip-10-0-0-177-12/firecracker-microvm/firecracker-go-sdk/machine_test.go:2260

        	Error:      	Received unexpected error:

        	            	dial tcp 10.168.0.3:22: connect: no route to host

        	Test:       	TestLoadSnapshot

time="2022-08-31T15:03:28Z" level=info msg="Sent instance shutdown request: [PUT /actions][204] createSyncActionNoContent "
```

This is a result of a bug in Firecracker's devtool causing the rootfs build to silently fail.

**Comment by fangn2** [comment]
As #488 merged, this issue can be closed as resolved.
