### ISSUE TITLE
Make test images step in pipeline is no longer doing useful work

### ISSUE THREAD

**Issue by austinvazquez** [firecracker-microvm/firecracker-go-sdk#422]
This feels like an example of code rot.

This [step](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/main/.buildkite/pipeline.yml#L48) builds firecracker and jailer binaries. However later in the pipeline we utilize `make deps` which downloads the latest firecracker and jailer binaries from release S3 bucket.

I would prefer removing the `test-images` target and step from the pipeline. This should speed up builds and makes pipeline runs consistent with local development.

**Comment by kzys** [comment]
I think, we are testing the SDK against Firecracker's release versions and it's main branch. The container is for the latter.

**Comment by austinvazquez** [comment]
@kzys, I see the step now which uses the main branch binaries. I was wrong.
