### ISSUE TITLE
MMDS should default to V2

### ISSUE THREAD

**Issue by protochron** [firecracker-microvm/firecracker-go-sdk#437]
Now that v2 of the MMDS is GA and v1 is deprecated, shouldn't the Go SDK default to V2? It seems like omitting the version parameter like the SDK does in he `setMmdsConfig` handler means that the Firecracker VMM is still using v1.

Seems like a fairly straightforward fix: just set the `Version` field in the `MmdsConfig` struct that is built in the handler. I'm just not sure if it's what you all want to default to right now or if there's another reason why that hasn't been updated.

**Comment by Joffref** [comment]
Knowing that MMDS V2 is available in firecracker (https://github.com/firecracker-microvm/firecracker/blob/e81013c5be768c96b9088869bf468c0954d74e3e/src/mmds/src/data_store.rs#L34-L41) I thinks it's possible to at least give the capability to SDK user to set themselves the version for MMDS and still defaulting to V1.

But I think there is more than the version field to change. According to this : https://github.com/firecracker-microvm/firecracker/blob/e81013c5be768c96b9088869bf468c0954d74e3e/src/mmds/src/data_store.rs#L13-L19 you also need to add a new field to the MmdsConfig config and I don't know if it will break the SDK or even if it's already implemented in the SDK.

I'm waiting for firecracker-go-sdk dev team thought on this but it could be a great feature
