### ISSUE TITLE
network configuration is not working

### ISSUE THREAD

**Issue by deepak6446** [firecracker-microvm/firecracker-go-sdk#50]
getting error
[PUT /network-interfaces/{iface_id}][400] putGuestNetworkInterfaceByIdBadRequest  &{FaultMessage:missing field `state` at line 1 column 71}
panic: failed to initialize machine: [PUT /network-interfaces/{iface_id}][400] putGuestNetworkInterfaceByIdBadRequest  &{FaultMessage:missing field `state` at line 1 column 71}

api is not getting state

**Comment by xibz** [comment]
Hello @deepak6446, thank you for reaching out to us. What version of firecracker are you using here? I recently tested this with `0.12.0` and everything seems to be working properly.

**Comment by deepak6446** [comment]
I cannot find key "state": "Attached" in network initalization
also if we could add an example in example.go it would be really helpful

**Comment by xibz** [comment]
@deepak6446 -  What version of [firecracker](github.com/firecracker-microvm/firecracker) are you using? It seems there may be a mismatch between the SDK and the version of what version of firecracker you are using.

**Comment by deepak6446** [comment]
@xibz i using firecracker-v0.11.0 
does that work with commit 1585d53 on gosdk

**Comment by xibz** [comment]
@deepak6446 - The current version of the SDK is compatible with v0.12. Can you update to v0.12 and let us know if that resolves the problem?

**Comment by samuelkarp** [comment]
@deepak6446 We haven't heard back from you in a while, so I'm going to close this issue.  If you have any further questions, please feel free to open a new issue.
