### ISSUE TITLE
Upgrade to firecracker v0.14.0

### ISSUE THREAD

**Issue by kshitij8** [firecracker-microvm/firecracker-go-sdk#51]
Firecracker v0.13.0 has been released: https://github.com/firecracker-microvm/firecracker/releases/tag/v0.13.0

**Comment by kshitij8** [comment]
The following command doesn't seem to be generating a [client](https://goswagger.io/generate/client.html) in sync with what we have right now:
`swagger generate client -f client/swagger.yaml -m client/models -r COPYRIGHT_HEADER`  

Any idea what was used for the previous runs?

**Comment by xibz** [comment]
Hello @kshitij8, thank you for reaching out to us. We currently use `make generate` to generate the SDK. If you run into any issue with that please let us know. My plan was to update to the newest swagger model when a couple of the PRs get merged. Otherwise there are going to be some merge conflicts, especially with the custom templates PR.

**Comment by kshitij8** [comment]
Hi @xibz,  
I'm probably missing something but with make generate I see the following:
```
make generate
go generate 
machine_test.go:14: running "mockgen": exec: "mockgen": executable file not found in $PATH
make: *** [generate] Error 1
```

**Comment by xibz** [comment]
@kshitij8 - Yea, generating the SDK requires `mockgen`.

You can install it by
```bash
go get github.com/golang/mock/gomock
go install github.com/golang/mock/mockgen
```

Ensure your `GOPATH`/bin is in `PATH` or `GOBIN` is pointing to a path in `PATH`.

**Comment by xibz** [comment]
Cannot update til' this [issue](https://github.com/firecracker-microvm/firecracker/issues/868) is resolved

**Comment by samuelkarp** [comment]
v0.14.0 appears to have issues with vsock; see https://github.com/firecracker-microvm/firecracker/issues/897 and https://github.com/firecracker-microvm/firecracker/issues/911.  I think we can still update the SDK, but downstream consumers of the SDK who depend on vsock (like [firecracker-containerd](https://github.com/firecracker-microvm/firecracker-containerd/)) will be blocked on upgrading until the issues are resolved.

**Comment by nmeyerhans** [comment]
We've skipped 0.14.0 and gone straight to 0.15.0, which is supported by the release we just issued (our first!). [v0.15.0](../releases/tag/v0.15.0)
