### ISSUE TITLE
API calls take exactly the timeout of time

### ISSUE THREAD

**Issue by samuelkarp** [firecracker-microvm/firecracker-go-sdk#52]
API calls made through the Unix socket appear to take exactly 500ms, which is the value of [`firecrackerRequestTimeout`](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/1585d53f793483c96d5d9058ca705d97d1b0558b/firecracker.go#L28).  I can observe this by manipulating the timeout in the [`runtime.ClientOperation`](https://github.com/firecracker-microvm/firecracker-go-sdk/blob/1585d53f793483c96d5d9058ca705d97d1b0558b/client/client_transports_test.go#L50).

**Comment by xibz** [comment]
I can't seem to reproduce this on my home machine. I pulled #53 locally and change the time to 5 minutes and moved the submit to a go routine and it passed o.o

**Comment by samuelkarp** [comment]
Can you try changing the time to 5 minutes without making any other changes?  Moving the submit to a goroutine would hide the symptom; the bytes are submitted to the socket effectively instantly (which is why I was able to get away with 1ms) but then submit continues to block until the timeout.
