### ISSUE TITLE
Unable to SSH into VM

### ISSUE THREAD

**Issue by utibeabasi6** [firecracker-microvm/firecracker-go-sdk#527]
Hello
i created a virtual machine on digital ocean and wrote some code with the GO sdk to create a vm
i am using CNI for networking but i cant seem to be able to ssh into my vm
and my vm has no cant communicate with the internet as well
I am happy to share my code 
I would appreciate any help

**Comment by utibeabasi6** [comment]
@bduffany @kzys @michaeldwan 
heres my cni configuration
```{
	"cniVersion": "0.4.0",
	"name": "fcnet",
	"plugins": [
		{
		"type": "ptp",
		"ipMasq": false,
		"ipam": {
			"type": "host-local",
			"subnet": "10.168.0.0/24",
			"routes":[{"dst":"0.0.0.0/0"}],
			"resolvConf": "/etc/resolv.conf"
		}
		},
		{
		  "type": "firewall"
		},
		{
		"type": "tc-redirect-tap"
		}
	]
	}```

i am unable to connect

**Comment by sagoresarker** [comment]
@utibeabasi6 how do you solve this issue? Could you please share the solution here?
