### ISSUE TITLE
Rethink signal handling

### ISSUE THREAD

**Issue by samuelkarp** [firecracker-microvm/firecracker-go-sdk#85]
Default signal handling in Linux could lead the `firecracker` process to become orphaned.  To prevent this, the SDK sets up some default signal handlers that forward signals along to the `firecracker` process.  However, this is pretty implicit and not super discoverable unless you read the code, and it may interfere with signal handling that the calling application intends to perform.  We should think about:

* what we want signal handling to be
* whether the SDK should register signal handlers by default
* how this can be made more explicit and less implicit

**Comment by rstat1** [comment]
If I may add my 2 cents as a user of firecracker and this sdk (in some personal experiments), my biggest issue with the SDK's signal handling is that it doesn't unset the handlers after the firecracker process goes away. This ended up interfering with some of my own signal handlers.

**Comment by evantorrie** [comment]
In my case, I want to control signal handling from my own process - I would rather have some option to disable the auto-signal handler creation inside the firecracker SDK.

**Comment by kzys** [comment]
How about having 

```
func (m *Machine) Close() error {
	if err := m.StopVMM(); err != nil {
		return err
	}
	return m.Wait(nil)
}
```

and let customers kill `firecracker` by closing the machine?

It is a bit cumbersome than our current signal handling, but more explicit and won't interfere with the host application's signal handling.

We currently try to free resources we made by assuming the application's signal handling policy, but we really don't know about. In Go, providing explicit `Close()` is more common way of doing that.

**Comment by jeromegn** [comment]
For what it's worth, we have a use-case where we do not want signals to be handled by firecracker-go-sdk since we sometimes want to orphan firecrackers and pick them back up later (we only really care about their PID and use meta data to recognize them).

It could be an option in the machine config.

**Comment by kzys** [comment]
I think #166 is good enough to close this issue.

Regarding the idea I proposed above, StopVMM() is killing a VM forcibly and we are trying to avoid using the method on firecracker-containerd. So calling this method `Close()` is bit misleading, since it is unsafe.

**Comment by samuelkarp** [comment]
@kzys I agree.  Closing this.
